export const routes = {
  homepage: "/",
  settings: "/account/settings",
  signup: "/account/signup",
  set_password: "/account/set-password",
  admin_access_requests: "/admin/access-requests",
  project_list: "/projects",
  project: "/projects/[projectId]",
  team: "/teams/[teamId]",
  teams: "/teams",
  project_analyses_list: "/projects/[projectId]/analyses",
  project_datasets_list: "/projects/[projectId]/datasets",
  project_dataset: "/projects/[projectId]/datasets/[datasetId]",
  project_analysis: "/projects/[projectId]/analyses/[analysisId]",
  project_analysis_edit: "/projects/[projectId]/analyses/[analysisId]/edit",
};
