# See https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run CI (lint & tests)

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - uses: actions/cache@v2
        id: cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm ci

      - run: npm run lint
        name: Lint Typescript files

      - run: npm run test:ci
        name: Run Tests

      - run: npm run i18n:extract
        name: Check I18N strings
        env:
          CI: true

      - run: npm run build
        name: Build
