# See https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Run CI (lint & tests)

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - run: npm run lint
        name: Lint Typescript files

      - run: npm run test:ci
        name: Run Tests

      - run: npm run i18n:extract
        name: Check I18N strings
        env:
          CI: true

      - run: npm run build
        name: Build
